version: "3.8"

services:

  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: 
      - ./envs/local/.mongo
    ports:
      - 27017:27017
    volumes:
      - db:/data/db
    command: mongod --quiet --logpath /dev/null 

  app:
    container_name: divors-back-app
    image: divors-back-app
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
      # target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./envs/local/.env
    ports:
      - 3333:3333

volumes:
  db: